export default types = {
  ADD_CARD_TO_WISHLIST: 'ADD_CARD_TO_WISHLIST',
  REMOVE_CARD_FROM_WISHLIST: 'REMOVE_CARD_FROM_WISHLIST',
  DECREMENT_CARD_ON_WISHLIST: 'DECREMENT_CARD_ON_WISHLIST',
  IMCREMENT_CARD_ON_WISHLIST: 'IMCREMENT_CARD_ON_WISHLIST',
  CLEAR_WISHLIST: 'CLEAR_WISHLIST',
}